<?php

// This file was generated by running "composer dump-env prod"

return array (
  'APP_ENV' => 'prod',
  'SYMFONY_DOTENV_PATH' => './.env',
  'APP_SECRET' => 'aeaf505228db7d0b9348f00df9c0432a',
  'DATABASE_URL' => 'mysql://grju2696_decide1983:!@D0nie21!@127.0.0.1:3306/grju2696_pillowinteractive?serverVersion=8.0.32&charset=utf8mb4',
  'MESSENGER_TRANSPORT_DSN' => 'doctrine://default?auto_setup=0',
);
